const brandedAmazonItems = [
  "airpods pro 2",
  "apple watch series 10",
  "apple watch ultra 2",
  "ipad mini",
  "ipad air",
  "ipad pro",
  "macbook air",
  "macbook pro",
  "kindle paperwhite",
  "kindle scribe",
  "kindle kids",
  "echo dot",
  "echo pop",
  "echo show 5",
  "echo show 8",
  "echo show 10",
  "echo studio",
  "fire tv stick 4k max",
  "fire tv cube",
  "fire hd 10 tablet",
  "ring battery doorbell plus",
  "ring floodlight cam",
  "ring alarm kit",
  "blink outdoor 4 camera",
  "eero pro 6e mesh wifi",
  "eero max 7 router",
  "sony wh-1000xm5",
  "sony wf-1000xm5",
  "bose quietcomfort ultra headphones",
  "bose quietcomfort earbuds ii",
  "jbl charge 5 speaker",
  "ultimate ears boom 3",
  "marshall emberton ii",
  "beats studio pro",
  "beats fit pro",
  "logitech mx master 3s",
  "logitech mx keys s",
  "logitech brio 4k webcam",
  "razer blackwidow v4",
  "razer deathadder v3",
  "steelseries arctis nova pro",
  "elgato stream deck mk2",
  "elgato key light air",
  "gopro hero 13",
  "insta360 x4",
  "fujifilm instax mini 12",
  "canon eos r50",
  "nikon z30",
  "anker prime power bank",
  "anker maggo battery",
  "belkin 3-in-1 charger",
  "baseus usb c hub",
  "ugreen nexode charger",
  "samsung t9 portable ssd",
  "sandisk extreme portable ssd",
  "wd black sn850x",
  "crucial x9 pro ssd",
  "dyson v15 detect",
  "dyson airwrap complete",
  "roborock s8 pro ultra",
  "irobot roomba j9+",
  "shark detect pro vacuum",
  "ninja creami deluxe",
  "ninja foodi pressure cooker",
  "instant pot duo plus",
  "breville barista express",
  "de'longhi dedica espresso machine",
  "philips air fryer xl",
  "cosori turbo blaze air fryer",
  "kitchenaid stand mixer",
  "vitamix e310 blender",
  "nutribullet pro",
  "fellow stagg kettle",
  "chemex coffee maker",
  "aeropress coffee maker",
  "hydro flask bottle",
  "stanley quencher tumbler",
  "yeti rambler tumbler",
  "lululemon everywhere belt bag",
  "samsonite carry-on",
  "away hard shell luggage",
  "patagonia black hole duffel",
  "north face borealis backpack",
  "herschel retreat backpack",
  "brooks ghost 16 running shoes",
  "hoka clifton 9",
  "on cloudmonster",
  "new balance 990v6",
  "crocs classic clogs",
  "dr martens 1460 boots",
  "birkenstock arizona",
  "ray-ban wayfarer",
  "oakley holbrook",
  "casio g-shock",
  "citizen eco-drive watch",
  "lego technic set",
  "lego star wars set",
  "pokemon elite trainer box",
  "nintendo switch oled",
  "xbox wireless controller",
  "playstation dualsense controller",
  "meta quest 3",
  "steam deck oled",
  "dji mini 4 pro",
  "yeti cooler",
  "coleman camping stove",
  "life straw water filter",
  "garmin fenix 8",
  "garmin forerunner 965",
  "withings body smart scale",
  "fitbit charge 6",
  "theragun mini",
  "renpho massage gun",
  "oral-b io toothbrush",
  "philips sonicare 9900",
  "waterpik flosser",
  "cerave skincare set",
  "la roche-posay sunscreen",
  "k18 hair mask",
  "olaplex hair kit",
  "laneige lip sleeping mask",
  "fenty beauty gloss bomb",
  "the ordinary skincare bundle",
  "tile mate tracker",
  "apple airtag 4 pack",
  "nanoleaf shapes light panels",
  "govee rgbic light strip",
  "philips hue starter kit",
  "tp-link kasa smart plug",
  "meross smart garage opener",
  "ecobee smart thermostat",
  "nest learning thermostat",
  "brother laser printer",
  "hp officejet pro",
  "fujitsu scansnap scanner",
  "reMarkable 2 tablet",
  "rocketbook smart notebook",
  "twelve south laptop stand",
  "human scale foot rest",
  "branch ergonomic chair",
  "herman miller chair",
  "secretlab titan evo",
  "purple harmony pillow",
  "casper mattress topper",
  "brooklinen sheet set",
  "ugg throw blanket",
  "dyson purifier fan",
  "levoit core 600s",
  "coway airmega purifier",
  "hatch restore sunrise alarm",
  "lofree mechanical keyboard",
  "nuphy air75 keyboard",
  "keychron q1 pro keyboard",
  "nomad magnetic wallet",
  "peak design tech pouch",
  "peak design everyday backpack",
  "tomtoc sling bag",
  "wacom intuos tablet",
  "xp-pen artist display",
];

const productTypes = [
  "noise cancelling headphones",
  "wireless earbuds",
  "portable speaker",
  "mechanical keyboard",
  "gaming mouse",
  "ergonomic mouse",
  "4k webcam",
  "usb c hub",
  "laptop stand",
  "monitor arm",
  "desk mat",
  "standing desk converter",
  "desk lamp",
  "smart light bulb",
  "rgb light strip",
  "smart plug",
  "smart thermostat",
  "security camera",
  "video doorbell",
  "mesh wifi router",
  "network switch",
  "portable ssd",
  "nvme ssd",
  "external hard drive",
  "power bank",
  "gan charger",
  "magnetic charger",
  "car charger",
  "travel adapter",
  "phone tripod",
  "camera sling bag",
  "camera backpack",
  "mirrorless camera",
  "action camera",
  "instant camera",
  "camera lens",
  "drone",
  "gimbal stabilizer",
  "stream deck",
  "podcast microphone",
  "audio interface",
  "ring light",
  "key light",
  "green screen",
  "gaming headset",
  "gaming controller",
  "vr headset",
  "gaming monitor",
  "mechanical pencil set",
  "fountain pen",
  "smart notebook",
  "tablet",
  "e-reader",
  "bluetooth tracker",
  "carry on suitcase",
  "travel backpack",
  "packing cubes",
  "duffel bag",
  "crossbody bag",
  "belt bag",
  "wallet",
  "passport holder",
  "running shoes",
  "walking shoes",
  "hiking shoes",
  "yoga mat",
  "resistance bands",
  "adjustable dumbbells",
  "kettlebell",
  "foam roller",
  "massage gun",
  "fitness watch",
  "smart scale",
  "air fryer",
  "espresso machine",
  "coffee grinder",
  "coffee maker",
  "electric kettle",
  "toaster oven",
  "blender",
  "food processor",
  "slow cooker",
  "pressure cooker",
  "rice cooker",
  "stand mixer",
  "chef knife set",
  "cast iron skillet",
  "nonstick pan set",
  "meal prep containers",
  "water bottle",
  "insulated tumbler",
  "lunch box",
  "vacuum sealer",
  "robot vacuum",
  "cordless vacuum",
  "air purifier",
  "humidifier",
  "dehumidifier",
  "space heater",
  "tower fan",
  "weighted blanket",
  "memory foam pillow",
  "sheet set",
  "mattress topper",
  "blackout curtains",
  "alarm clock",
  "digital photo frame",
  "lego set",
  "board game",
  "puzzle set",
  "kids tablet",
  "baby monitor",
  "stroller organizer",
  "pet camera",
  "pet water fountain",
  "cat tree",
  "dog bed",
  "wireless printer",
  "label maker",
  "paper shredder",
  "document scanner",
  "fireproof safe",
  "tool kit",
  "drill set",
  "jump starter",
  "dash cam",
  "camping stove",
  "portable grill",
  "cooler",
  "hammock",
  "sleeping bag",
  "tent",
  "flashlight",
  "bike helmet",
  "electric scooter helmet",
  "phone case",
  "screen protector",
  "tablet case",
  "stylus pen",
  "drawing tablet",
  "led neon sign",
  "wall art set",
  "shoe rack",
  "clothing rack",
  "laundry hamper",
  "storage bins",
  "under bed organizer",
];

const descriptors = [
  "compact",
  "premium",
  "budget",
  "luxury",
  "minimal",
  "portable",
  "travel",
  "wireless",
  "smart",
  "quiet",
  "durable",
  "eco friendly",
  "fast charging",
  "high fidelity",
  "ergonomic",
  "waterproof",
  "sleek",
  "pro",
  "ultra",
  "lightweight",
  "heavy duty",
  "magnetic",
  "refurbished",
  "giftable",
  "best selling",
  "editor approved",
];

const useCases = [
  "remote work",
  "content creators",
  "podcasting",
  "gaming",
  "travel days",
  "small apartments",
  "student life",
  "daily commute",
  "home office",
  "late night study",
  "morning workouts",
  "meal prep",
  "coffee lovers",
  "pet owners",
  "new parents",
  "apartment kitchens",
  "side hustles",
  "minimal desks",
  "weekend trips",
  "road trips",
  "video calls",
  "smart homes",
];

const contexts = [
  "bedroom",
  "living room",
  "kitchen",
  "dorm room",
  "office desk",
  "studio apartment",
  "garage",
  "car",
  "travel bag",
  "carry on",
  "gym bag",
  "game room",
  "creator studio",
  "workstation",
  "weekend cabin",
  "tiny home",
];

function buildAmazonBuyLibrary() {
  const suggestions = new Set<string>();

  for (const item of brandedAmazonItems) {
    suggestions.add(item);
  }

  for (const descriptor of descriptors) {
    for (const productType of productTypes) {
      suggestions.add(`${descriptor} ${productType}`);
    }
  }

  for (const productType of productTypes) {
    for (const useCase of useCases) {
      suggestions.add(`${productType} for ${useCase}`);
    }
    for (const context of contexts) {
      suggestions.add(`${productType} for ${context}`);
    }
  }

  return Array.from(suggestions).filter((entry) => entry.length <= 74);
}

export const AMAZON_BUY_LIBRARY = buildAmazonBuyLibrary();
